<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYUQmgF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYUQmgF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYUQmgF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYUQmgF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYUQmgF\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYUQmgF',
    'container.build_id' => '53fd5c83',
    'container.build_time' => 1658262049,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYUQmgF');
